#+hugo_base_dir: ../

* DONE My first post :tag1:@category1:
CLOSED: [2024-09-12 Thu 02:31]
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
- State "DONE"       from "BLOCKED"    [2024-09-12 Thu 02:31]
- State "VERIFYING"  from "IN-PROGRESS" [2024-09-12 Thu 02:30]
This is my post body. This is entirely written in Emacs. Using emacs and ox-hugo is the quickest and easiest way to create a website.
The quick brown fox jumped over the white fence.


* IDEA Emacs  for Students
:PROPERTIES:
:ID:       o2b:69af2404-c6a7-4372-a9e1-23aa7939de84
#+DATE: [2024-09-13 Fri 19:40]
:EXPORT_FILE_NAME: emacs-for-students
#+TITLE: Emacs  for Students
:POST_DATE: [2024-09-13 Fri 22:18]
:END:

Easily get an A+ with Emacs.
If you are set on a career in research, then you are up for the long-term. Future proofing your data should be your first concern. Proprietary files will lock you from accessing your collected data. Instead text file is the way to go, and Emacs got you covered.

** Notetaking

**  Writing

**  Research

**  Bibliography and Citations

**  Exporting to PDF and Word

**  Exporting to Presentation
Are you ready to present your research to the public? Emacs has packages to help your make presentations instantly. With Org-reveal, your org file can convert into HTML-based presentation which you can show using a browser.
