baseURL = 'https://github.com/susancorpuz/mandiga.github.io/'
languageCode = 'en-us'
title = 'Mandiga Info'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

 theme = "PaperMod"

 [markup.goldmark.renderer]
