[build]
  base = "quickstart"
  publish = "public"           # <-- change from "quickstart/public"
  command = "hugo mod get && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.146.7"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21"
